version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./model_artifacts:/model_artifacts
      - ./get-fit-life.pdf:/get-fit-life.pdf
    command: uv run fastapi run src/main.py --host 0.0.0.0 --port ${PORT:-8000}
